### ISSUE TITLE
Course listing details is hiding non-visible courses

### ISSUE THREAD

**Issue by shadinaif** [nelc/futurex-openedx-extensions#12]
https://github.com/nelc/futurex-openedx-extensions/blob/5c1c0c8aa08d21c206424c0c2f3d4a8cfef1da61/futurex_openedx_extensions/dashboard/views.py#L129

this should not hide non-visible courses. And must add a `visibility` field to the response

Also course statuses must show count of hiden separately

**Comment by OmarIthawi** [comment]
@shadinaif this is still the case on production, please check:

 - Shows four courses, even on the course listing page.
 - Studio shows much more courses for SREI.

![image](https://github.com/nelc/futurex-openedx-extensions/assets/645156/524e2700-b67f-4842-8e19-907d8ce44f78)

**Comment by OmarIthawi** [comment]
The courses page is great. It shows the important courses first. However, we'd like to show the other (hidden from students) courses below so authors can use this instead of Studio.

@shadinaif so regarding the course list it's a bug in production.

Please fix after the Student Course details:

![image](https://github.com/nelc/futurex-openedx-extensions/assets/645156/d5386c22-7d4a-4d9e-83d3-0c5d29e28a54)

If you think the solution is complex, please ping Faris or Ahmed on Slack to discuss the possible UX implications.

**Comment by OmarIthawi** [comment]
Still a bug in production @shadinaif with v0.3.4:

![image](https://github.com/nelc/futurex-openedx-extensions/assets/645156/d071d473-4282-4444-ab6c-e68704ceef35)

**Comment by shadinaif** [comment]
resolved here https://github.com/nelc/futurex-openedx-extensions/pull/33

**Comment by OmarIthawi** [comment]
@shadinaif please check it out in production.
